# Generated by Django 5.1.6 on 2025-02-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hors",
            name="image_url",
        ),
        migrations.AddField(
            model_name="hors",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/horse/"),
        ),
    ]
