# Generated by Django 5.1.6 on 2025-02-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0002_remove_hors_image_url_hors_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hors",
            new_name="Horse",
        ),
    ]
