# Generated by Django 5.1.6 on 2025-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0003_rename_hors_horse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/products/"
            ),
        ),
    ]
