# Generated by Django 5.1.6 on 2025-02-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0004_remove_product_image_url_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
