# Generated by Django 5.1.6 on 2025-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0005_remove_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="horse",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
