# Generated by Django 5.1.6 on 2025-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apishop", "0006_alter_employees_id_alter_horse_id_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employees",
            name="description",
        ),
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
